### ISSUE TITLE
in_tagged_udp.rb:2:in `<module:Fluent>': uninitialized constant Fluent::Input (NameError)

### ISSUE THREAD

**Issue by Thiha-Aung1** [toyokazu/fluent-plugin-json_udp#1]
/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-tagged_udp-0.0.7/lib/fluent/plugin/in_tagged_udp.rb:2:in `<module:Fluent>': uninitialized constant Fluent::Input (NameError)

from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-tagged_udp-0.0.7/lib/fluent/plugin/in_tagged_udp.rb:1:in `<top (required)>'

from /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'

from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.1/lib/fluent/registry.rb:102:in `block in search'

from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.1/lib/fluent/registry.rb:99:in `each'

from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.1/lib/fluent/registry.rb:99:in `search'

from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.1/lib/fluent/registry.rb:44:in `lookup'

**Comment by Thiha-Aung1** [comment]
i solved it
